### PR TITLE
Update context.version, fix scoreboard conflicts with PlayerJoin, add "rejoin" method to PlayerJoin

### PR DESCRIPTION
**Pull request by Synthetic-Dev**
Updated the context.version default and checks for 1.18 formatting, fixed scoreboards being overridden when an operation is used on them before they are added to the tree. Added a "rejoin" method to PlayerJoin that takes the behaviour of the default PlayerJoin constructor, which now accounts for when the player first joins the world.

### CODE REVIEW

**Review by Stevertus — CHANGES_REQUESTED** [review]
Please remove the debug messages again.
Otherwise great additions and fixes. Will definitely be in the next version

**Comment by Synthetic-Dev** [comment]
The debug messages are removed in the `Fix scoreboard overwrites` commit

**Comment by Stevertus** [comment]
> The debug messages are removed in the `Fix scoreboard overwrites` commit

A yes sorry you are right. But in the same commit is the `removeOld`` really needed? In which cases do you use it and why not simple Scoreboard.remove?

**Comment by Synthetic-Dev** [comment]
It is just a feature that I am using in a datapack for convenience, do you want it removed?

**Review by Stevertus — APPROVED** [review]

**Comment by Stevertus** [comment]
Is that solely for easier debugging, when changing the type? As said I don't see a use case other than multiple scoreboards with different types generated and thus removed it

**Pull request merged**
